id: 62
user: eq19
span: span-43
title: eQuantum
baseurl: /wikibox
repository: HybridModels/wikibox
action: HybridModels/webpack/actions/runs/15178748578
description: ₠Quantum Project

#debug:
#  dist: false
#  compress: true
#  shortcodes: true

lsi: false
incremental: true
highlighter: rouge
plugins_dir: _plugins

gist:
  noscript: false

kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

readme_index:
  with_frontmatter: true

exclude:
  - LICENSE
  - vendor/
  - action.yml  
  - Dockerfile

plugins:
  - jemoji
  - jekyll-gist
  - jekyll-avatar
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-coffeescript
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-relative-links
  - jekyll-github-metadata
  - jekyll-titles-from-headings
  - jekyll-optional-front-matter

track:
  spin: [4, 9]
  pinned: [maps, feed, lexer, parser, syntax, grammar, falcon, webpack, wikibox, transparency, flavio, ta-lib]
  organization: [Chetabahana, FeedMapping, GlobalZones, HybridModels, JunctionTerms, KernelPatterns, MappingSystem, NeuralSystem, ObjectModules, VirtualNetworks, WeakNegative, WeakPositive, ZeroWeak]
